### ISSUE TITLE
Avif on the fly

### ISSUE THREAD

**Issue by Pijushgupta** [Pijushgupta/avif-express#2]
Avif generation on the fly not working

**Comment by ankusa** [comment]
Yes It's not working

**Comment by Pijushgupta** [comment]
> Yes It's not working

can you please provide the PHP GD lib version ?

**Comment by Pijushgupta** [comment]
Bux fix: https://github.com/Pijushgupta/avif-express/commit/5f1530656e95c1b4c84367dfdae2fdbcf4b7beb5
