### ISSUE TITLE
Very promising but is it abandoned? In case not a number of issues...

### ISSUE THREAD

**Issue by tomasts248** [Pijushgupta/avif-express#3]
Hi, first thank you for dev this, question are you providing support for this?
If yes, I have a number of issues:
 1. The converting process gets stuck (there's an error in the console not sure if related)
   `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
 3. No logs?
 4. When using rendering I'm getting 500 error.
 Kind Regards

**Comment by Pijushgupta** [comment]
No its not abandoned! That a Bug(image.php line 155) due to Image Magic (7.0.25) Avif file type setting. There is no workaround. That issue got fixed in Image Magic 7.1.x.

**Comment by tomasts248** [comment]
> No its not abandoned!

Ahh great :)

> That is a Bug(image.php line 155) due to Image Magic (7.0.25) Avif file type setting. There is no workaround. 

I see..

> Any help appreciated.

Wish I could but I'm not sure how really, oddly is a very old bug.. 

> It does not actually create the .avif, but just copies it as jpeg and changes the file extension

Ok did some checking at least the image created as avif are not the same size as the original source images.. so perhaps is not the same linked issue?

**Comment by Pijushgupta** [comment]
> Ok did some checking at least the image created as avif are not the same size as the original source images.. so perhaps is not the same linked issue? Most likely I'm wrong though.. There are some webp and avif images with 0 file size though..
Okay, are you sure its being processed by ImageMagic? Usually GD creates empty images in some cases. I had that issue before but unable recreate that. GD being in use as fallback of ImageMagic. Going remove GD logic in the upcoming updates

**Comment by Snippet24816** [comment]
I'm sorry my ignorance but how do you check that? at least the module in cpanel is enabled. May suggest perhaps some log in the plugin so that we can tell whats happening behind the scenes.

**Comment by tomasts248** [comment]
I'm sorry my ignorance but how do you check that? at least the module in cpanel is enabled. May suggest perhaps some log in the plugin so that we can tell whats happening behind the scenes.

**Comment by Pijushgupta** [comment]
> I'm sorry my ignorance but how do you check that? at least the module in cpanel is enabled. May I suggest perhaps some log in the plugin so that we can tell whats happening behind the scenes.

logs for user : great idea, going to implement ASAP

**Comment by Pijushgupta** [comment]
Logging added
