### ISSUE TITLE
AVIF is not working.

### ISSUE THREAD

**Issue by ankusa** [Pijushgupta/avif-express#4]
AVIF Express is a powerful file format converter, however, it is currently not supported by any web browser.

**Comment by VilterPD** [comment]
Do you mean the Plugin or the Picture Format? Because both seem to be supported[Avif made by AVIFexpress](https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen.avif)
