### ISSUE TITLE
Avif not added to srcset

### ISSUE THREAD

**Issue by VilterPD** [Pijushgupta/avif-express#5]
Hi, thanks for the great and simple Plugin

All the .avif seem to be generated [Example](https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen.avif) but not added to my srcset. I even coded my own integration into srcset on ACCEPT-Header, no luck. Any ideas?
`
<img width="1600" height="600" src="[https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen.jpg](view-source:https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen.jpg)" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="Click A Tree, Destinaries und Trauminsel Reisen" itemprop="image" decoding="async" fetchpriority="high" srcset="https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen.jpg 1600w, https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen-300x113.jpg 300w, https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen-1024x384.jpg 1024w, https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen-768x288.jpg 768w, https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen-1536x576.jpg 1536w" sizes="(max-width: 1600px) 100vw, 1600px" title="Click A Tree, Destinaries und Trauminsel Reisen 1">	</figure>`

P.S.: Sorry I left my question at the wrong place, I only found this after, feel free to delete the other instance.

**Comment by Pijushgupta** [comment]
> Hi, thanks for the great and simple Plugin
> 
> All the .avif seem to be generated [Example](https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen.avif) but not added to my srcset. I even coded my own integration into srcset on ACCEPT-Header, no luck. Any ideas? ` <img width="1600" height="600" src="[https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen.jpg](view-source:https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen.jpg)" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="Click A Tree, Destinaries und Trauminsel Reisen" itemprop="image" decoding="async" fetchpriority="high" srcset="https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen.jpg 1600w, https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen-300x113.jpg 300w, https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen-1024x384.jpg 1024w, https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen-768x288.jpg 768w, https://www.trauminselreisen.de/blog/wp-content/uploads/2023/08/Click-A-Tree-Trauminsel-Reisen-1536x576.jpg 1536w" sizes="(max-width: 1600px) 100vw, 1600px" title="Click A Tree, Destinaries und Trauminsel Reisen 1"> </figure>`
> 
> P.S.: Sorry I left my question at the wrong place, I only found this after, feel free to delete the other instance.

can you please test with the recent version  ?
