### ISSUE TITLE
webP fallback

### ISSUE THREAD

**Issue by Troglos** [Pijushgupta/avif-express#7]
This is not a criticism, I am trying to help improve this great plugin  ;)
Testing the plugin on 2 different sites using Firefox with image.avif.enabled = false

Site 1 with no cache: 
it tries to load https://website.it/wp-content/uploads/foto-idee.webp that doesn't exist, because I see on the server that the image formats are just the original jpg (or png) and avif. No webp found. 

In my opinion it would be useful for the browser that don't support avif having the original jpg as a fallback, instead of adding webP and increasing the size of the upload folder.

Site 2 with LiteSpeed cache: 
when using LiteSpeed Cache the browser will always try to serve the avif version. It would be useful to add a cookie like "avif_support_false" for the browsers that don't support avif, so that the cache could be disabled in the LiteSpeed settings if this cookie exists.

Let me know if you need more details.

**Comment by Troglos** [comment]
1) It would be great if you can add this option. 
The problem is that no webp are generated in my test. Plus having original, webp and avif for each size would be really a lot for sites with many many images. In my case just avif + original as fallback it's enough.

2) With a cookie like "avif_support_false" it should be possible with any good caching solution I think. You just need to tell the caching plugin not to cache a site if that cookie is present.

**Comment by Pijushgupta** [comment]
1. Option to set fallback image type 
<img width="954" alt="image" src="https://github.com/Pijushgupta/avif-express/assets/1472227/0ef44714-c426-43c9-9e0f-2e3766252eca">

2. `browser-avif-support` cookie added. Possible value - true or false based on browsers avif support.

**Comment by Pijushgupta** [comment]
1. gonna update the code ASAP.
2. I'm working on the cloud part, that is why. I don't want users to register for the cloud service for now. Link will be active on RC candidate.

**Comment by Troglos** [comment]
I will test the new version soon,
Meanwhile I've noticed a *Fatal error*  error in the documentation page.




[image: Lino Sabato]
Lino Sabato
Freelance Web Developer

+39 329 627 7257
info@@kobalt.it ***@***.***>
kobalt.it
[image: Rating stars]
48 recensioni <https://g.page/r/CWDdS0mvMkcQEBM/review>


Il giorno sab 1 giu 2024 alle ore 19:08 Pijush Gupta <
***@***.***> ha scritto:

**Comment by Pijushgupta** [comment]
Thanks @Troglos for the update about the doc site. I'm working on it and it should be done in about 5 minutes.

Thanks for testing out the plugin. Please create an issue if you find anything that's not working.

**Comment by Pijushgupta** [comment]
issue finally fixed
