### ISSUE TITLE
500 wordpress error after updating

### ISSUE THREAD

**Issue by Joonas12334** [Pijushgupta/avif-express#9]
update 19.06.2024 breaks my site with an unrecoverable fatal server error 500.

reversed back to 28.06.2023 from snapshot which is just fine.

**Comment by Pijushgupta** [comment]
can you please share more info about the same, 
Like php version , wordpress version and more details about the error.

**Comment by Joonas12334** [comment]
Site info: https://i.imgur.com/FyrVSXb.png
Server info: https://i.imgur.com/O2donWF.png

This error seems to pop up after updating the plugin `<html>
<body>

2024/06/22 13:28:57 | stdout | [Sat Jun 22 10:28:57.527104 2024] [php:error] [pid 21] [client 81.90.114.35:0] PHP Fatal error:  Declaration of WooCommerce\\WooCommerce\\Logging\\Logger\\WooCommerceLogger::log($level, $message, array $context = []) must be compatible with Psr\\Log\\LoggerTrait::log($level, Stringable\|string $message, array $context = []): void in /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/woocommerce-logging/src/Logger/WooCommerceLogger.php on line 58, referer: https://wordpress.alphabetfilms.eu/wp-admin/plugins.php
-- | -- | --



</body>
</html>`

Also i'm using breakdance builder with wp rocket cache

**Comment by Pijushgupta** [comment]
Awesome, please wait 1-2 hrs, pushing new update to wordpress repository with the fix.  
The issue is with woocoomerce logger. 
This Avif express plugin also using psr/log as dependency for monolog as woocommerce logger. Removing monolog in favor of deafult php error_log function. Since monolog requires php ver >= 8.1

**Comment by Joonas12334** [comment]
Perfect! It works now. Thank you so much for the awesome plugin!
